## -*- docker-image-name: "scaleway/moul-testing-image-subdir:latest" -*-
FROM scaleway/ubuntu:trusty
MAINTAINER Scaleway <opensource@scaleway.com> (@scaleway)

RUN echo "Hello world from subdir!"
RUN date
